---
title: "Proyecto Alacranes"
author: "Eduardo Sclavo Melo - 136646"
date: "25 de octubre de 2014"
output: html_document
---

```{r Ajustes, echo = FALSE, message = FALSE, results = 'hide'}
directorio <- "/Users/jcdf_resident/Documents/ITAM/Estadística Aplicada I/Proyecto"
setwd(directorio)
knitr::opts_knit$set(root.dir = directorio)

knitr::opts_chunk$set(fig.path = "GRAFICAS/FINALES/Figuras_", fig.align = 'center',
                      fig.width = 12, fig.height = 8, 
                      cache.path = "CACHE/Cache_", cache = TRUE, 
                      eval = TRUE, 
                      warning = FALSE, message = FALSE,
                      echo = TRUE, 
                      comment = NA)

```

```{r Instalación de paquetes por utilizar}
paquetes.utilizados <- c("plyr", "tidyr", "dplyr", "lubridate", "ggplot2", "knitr")
paquetes.instalados <- rownames(installed.packages())
paquetes.por.instalar <- setdiff(paquetes.utilizados, paquetes.instalados)

# Instala los paquetes faltantes.
if (length(paquetes.por.instalar) != 0 ) install.packages(paquetes.por.instalar)

# Carga los paquetes a utilizar.
lapply(paquetes.utilizados, library, character.only = TRUE)
```

```{r Lectura de todos los achivos}

grupo <- NULL

##Lectura de archivos con estructura de control for
for (i in 1:11){
grupo[[i]] <- read.csv(paste("./DATOS/BRUTOS/GP/",i+2002,"G.csv",sep=""),sep=",", header= TRUE,stringsAsFactors=TRUE)
grupo[[i]]$ano <- as.numeric(2002+i)
grupo[[i]]$tipo <- "General"
}

for (i in 12:22){
grupo[[i]] <- read.csv(paste("./DATOS/BRUTOS/GP/",i+1991,"H.csv",sep=""),sep=",", header= TRUE,stringsAsFactors=TRUE)
grupo[[i]]$ano <- as.numeric(1991+i)
grupo[[i]]$tipo <- "Hombres"
}

for (i in 23:33){
grupo[[i]] <- read.csv(paste("./DATOS/BRUTOS/GP/",i+1980,"M.csv",sep=""),sep=",", header= TRUE,stringsAsFactors=TRUE)
grupo[[i]]$ano <- as.numeric(1980+i)
grupo[[i]]$tipo <- "Mujeres"
}

for(i in 1:33){
  names(grupo[[i]]) <- c("Estado","Menor a 1","Entre 1 y 4","Entre 5 y 9","Entre 10 y 14","Entre 15 y 19","Entre 20 y 24","Entre 25 y 44","Entre 45 y 49","Entre 50 y 59","Entre 60 y 64","Mayor a 65","Ign","Total","Ano","Tipo")
}
class(grupo)

##Creación del data frame con los todos los archivos juntos
grupo <- ldply(grupo,data.frame)
head(grupo)

##Cambiamos la clase de las columnas Estado, Ano y Tipo a factor
grupo$Estado <- as.factor(grupo$Estado)
grupo$Estado <- ordered(grupo$Estado)
grupo$Ano <- as.factor(grupo$Ano)
grupo$Ano <- ordered(grupo$Ano)
grupo$Tipo <- as.factor(grupo$Tipo)
grupo$Tipo <- ordered(grupo$Tipo)

str(grupo)

```

```{r Limpieza de datos}

## Queremos limpiar esta variable de forma que solo nos queden 33 categorías en Estado(cada uno de los 32 estados y un Total)
unique(grupo$Estado)
grep(".*M.x.*",grupo$Estado, value=TRUE)
grupo$Estado <- gsub(".*M.x.*","Mexico",grupo$Estado)
grupo$Estado <- gsub(".*Mich.*","Michoacan",grupo$Estado)
grupo$Estado <- gsub(".*San.*","San Luis Potosi",grupo$Estado)
grupo$Estado <- gsub(".*Nue.*","Nuevo Leon",grupo$Estado)
grupo$Estado <- gsub(".*Yuc.*","Yucatan",grupo$Estado)
grupo$Estado <- gsub(".*Quer.*","Queretaro",grupo$Estado)
grupo$Estado <- gsub(".*Tot.*|.*TOT.*","Total",grupo$Estado)
grupo$Estado <- gsub(".*Su.*","Baja California Sur",grupo$Estado)
grupo$Estado <- gsub(".*M./.*","Mexico",grupo$Estado)
grep(".*GLOBAL.*",grupo$Estado, value=TRUE)
grupo$Estado <- gsub(".*GLOBAL.*","Total",grupo$Estado)
grupo$Estado[345] <- "Mexico"
grupo$Estado[411] <- "Mexico"

unique(grupo$Estado)
grupo$Estado <- as.factor(grupo$Estado)
grupo$Estado <- ordered(grupo$Estado)
```

```{r Validación de datos}

## Número total de faltantes
sum(is.na(grupo))

## Completitud
mean(is.na(grupo))

##Proporción de registros faltantes por variable
sapply(grupo, function(x) {mean(is.na(x))})

##Número registros duplicados
sum(duplicated(grupo))

##Proporción de registros duplicados
mean(duplicated(grupo))


##Verficación que total de intoxicaciones por año es igual a la suma de los hombres más las mujeres intoxicadas cada año 

x <- 1:11
a <- 33*x
y <- 12:22
b <- 33*y
z <- 23:33
c <- 33*z

pic.tot <- grupo$Total[a]
pic.tot.H <- grupo$Total[b]
pic.tot.M <- grupo$Total[c]
pic.tot.validacion <- pic.tot.H+pic.tot.M
ANO <- unique(grupo$Ano)
validacion <- data.frame(ANO,pic.tot,pic.tot.validacion,stringsAsFactors=FALSE)
validacion

```

```{r Creacion de data frame modificado}

## Quitamos los 33 renglones que contienen Total para poder realizar algunas gráficas por estado y por año ilustrativas
grupo.A <- subset(grupo,Estado!="Total")

## Ahora nos quedamos con un data frame donde Tipo solo contenga datos Generales
grupo.A2 <- subset(grupo.A,Tipo!="Hombres" & Tipo!="Mujeres")


```

```{r Gráfica 1 con data frame A.2}

f <- function(x) {
  r <- quantile(x, probs = c(0.0, 0.25, 0.5, 0.75, 1))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

Mybreaks <- 1:65

Mybreaks <- 1000*Mybreaks


ggplot(grupo.A2, aes(x = Ano, y = Total, fill=Ano ))+stat_summary(fun.data = f, geom="boxplot")+labs(title = "Boxplots Intoxicacion por picaduras de alacran cada Ano (2003-2013)",x="Ano",y = "No.de Intoxicaciones")+scale_y_continuous("No.de Intoxicaciones",breaks=Mybreaks) + guides(fill = FALSE)

```

```{r Gráfica 2 , agrupando por estados, usando data frame A.2 }

ggplot(grupo.A2, aes(Ano, Total,group=Estado)) +
geom_line(data = grupo.A2, aes(colour = Estado)) +  
guides(colour = FALSE)+  
facet_wrap(~ Estado, ncol = 4) + 
  labs(title = "Intoxicacion por picadura de alacran por Entidad de 2003 a 2013", 
     x = "Ano", 
     y = "Numero de Intoxicaciones") + 
theme_bw() +
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.25), 
      strip.text = element_text(face = "bold"), 
      strip.background = element_blank(),
      panel.border = element_rect(colour = grey(.90)), 
      axis.ticks = element_line(colour=grey(.90), size = .5), 
      axis.text = element_text(colour=grey(.55)), 
      axis.title = element_text(colour=grey(.45)), 
      legend.key = element_blank())  

```

```{r Creación de nuevos data frame y grafica de las de intoxicaciones por ano agrupadas por edades}

##Pasamos al formato largo del data frame, ya que al querer graficar los distintos rangos de edades necesitamos que las edades no nos queden en distintas columnas, sino en una sola que denotaremos Rango.edades

grupo.B <- gather(data=grupo.A2, key="Rango.edades", value= "Valor", 2:13)
grupo.B$Total <- NULL

grupo.B$Estado <- NULL

##Suammos lo contenido en la comuna Valor conservando las otras 3 columnas del data frame
grupo.B11 <- aggregate(.~(Rango.edades+Tipo+Ano), grupo.B,sum)

str(grupo.B11)



ggplot(grupo.B11, aes(Ano, Valor,group=Rango.edades)) +
geom_line(data = grupo.B11, aes(colour = Rango.edades)) +  
guides(colour = FALSE)+  
facet_wrap(~ Rango.edades, ncol = 4) + 
  labs(title = "Intoxicacion por picaduras de alacran por edad 2003-2013", 
     x = "Ano", 
     y = "Numero de intoxicaciones") + 
theme_bw() +
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.25), 
      strip.text = element_text(face = "bold"), 
      strip.background = element_blank(),
      panel.border = element_rect(colour = grey(.90)), 
      axis.ticks = element_line(colour=grey(.90), size = .5), 
      axis.text = element_text(colour=grey(.55)), 
      axis.title = element_text(colour=grey(.45)), 
      legend.key = element_blank())  


```

```{r  Nuevo data frame  para grafica de picaduras dependiendo de la edad distinguiendo género}

##Queremos un data frame que en la comuna Tipo solo contenga las categorías Hombres y Mujeres
grupo.C <- subset(grupo.A,Tipo!="General")


##Usamos la función gather para pasar a la forma larga del data frame pues queremos graficar las picaduras de acuerdo a los intervalos de edad
grupo.C1 <- gather(data=grupo.C, key="Rango.edades", value= "Valor", 2:13)
grupo.C1$Total <- NULL
grupo.C1$Estado <- NULL
grupo.C1$Ano <- NULL

## Sacamos la suma de todas las picaduras agrupando por edad e Tipo
grupo.C1 <- aggregate(.~Rango.edades+Tipo, grupo.C1,sum)
?aggregate
str(grupo.C1)




ggplot(grupo.C1,aes(x=Rango.edades,y=Valor,fill=Tipo))+
       geom_bar(stat="identity", position="dodge")+
         theme_bw()+
         theme(axis.title.x=element_blank(),axis.title.y=element_blank())+
                 ggtitle("Intoxicacion por picadura de alacran por edad y genero")+
                 theme(plot.title=element_text(face="bold"))+
                      scale_y_continuous(breaks=seq(0,9990000,20000), options(scipen=7))+
                      scale_fill_manual(values=c("blue","red"))
         


```

```{r Gráfica que muestra las intoxicaciones por estado en la edad con mayor intoxicaciones,es decir, entre 25 y 44 anos}

##Pasamos al formato largo para poder graficar las intoxicaciones a distintas edades
grupo.G<- gather(data=grupo.A2, key="Rango.edades", value= "Valor", 2:13)
grupo.G$Total <- NULL

## Solo queremos quedarnos con un data frame con Rando de edades entre 25 y 44
grupo.Z <- subset(grupo.G,Rango.edades=="Entre.25.y.44")
Mybreaks <- 1:7
Mybreaks <- 2500*Mybreaks

ggplot(grupo.Z, aes(x = Ano, y =Valor ))+labs(title = "No. de intoxicaciones por picaduras de alacran por Estado y por ano para edad 25 a 44",x="Ano",y = "No.de Intoxicaciones ")+geom_line(data = grupo.Z, aes(x= Ano, y= Valor,group=Estado, colour = Estado))+scale_y_continuous("No.de Intoxicaciones",breaks=Mybreaks) + guides(fill = FALSE)

```

```{r Creación de nuevo data frame y gráfica de total de intoxicaciones dependiendo de la edad y del estado}

grupo.X <- subset(grupo.A,Tipo=="General")
grupo.X$Ano <- NULL
grupo.X$Total <- NULL

grupo.X1 <- gather(data=grupo.X, key="Rango.edades", value= "Valor", 2:13)

grupo.X1 <- aggregate(.~(Rango.edades+Tipo+Estado), grupo.X1,sum)


ggplot(grupo.X1, aes(Rango.edades, Valor,group=Estado)) +
geom_bar(data = grupo.X1, aes(colour = Estado),stat="identity", position="dodge") +  
guides(colour = FALSE)+  
facet_wrap(~ Estado, ncol = 4) + 
  labs(title = "Intoxicacion por picadura de alacran por Entidad y por Edad  de 2003 a 2013", 
     x = "Edad", 
     y = "Numero de Intoxicaciones") + 
theme_bw() +
theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.25), 
      strip.text = element_text(face = "bold"), 
      strip.background = element_blank(),
      panel.border = element_rect(colour = grey(.90)), 
      axis.ticks = element_line(colour=grey(.90), size = .5), 
      axis.text = element_text(colour=grey(.55)), 
      axis.title = element_text(colour=grey(.45)), 
      legend.key = element_blank())  

```

```{r Archivos procesados}

write.table(grupo, file="./DATOS/PROCESADOS/ReportePorEdades.csv",sep = ",", row.names=FALSE)

write.table(grupo.G, file="./DATOS/PROCESADOS/ReportePorAnoGrupo.csv",sep = ",", row.names=FALSE)

```

```{r Informción de la sesión}
sessionInfo()
```
