---
title: "Untitled"
author: "Juan Carlos Díaz Flores         c.u:000132965"
date: "24 de octubre de 2014"
output: html_document
---

```{r Ajustes, echo = FALSE, message = FALSE, results = 'hide'}
library(knitr)
directorio <- "/Users/jcdf_resident/Documents/ITAM/Estadística Aplicada I/Proyecto/DATOS/BRUTOS"
setwd(directorio)
knitr::opts_knit$set(root.dir = directorio)

knitr::opts_chunk$set(fig.path = "FIGURAS/Figuras_", fig.align = 'center',
                      fig.width = 12, fig.height = 8, 
                      cache.path = "CACHE/Cache_", cache = TRUE, 
                      eval = TRUE, 
                      warning = FALSE, message = FALSE,
                      echo = TRUE, 
                      comment = NA)

```

```{r Prueba}
install.packages("knitr")
install.packages("plyr")

mes <- NULL

for (i in 1:11){
mes[[i]] <- read.csv(paste("./MES/", i+2002,"G.csv",sep=""),sep=",", header= TRUE,stringsAsFactors=TRUE)
mes[[i]]$ano <- as.numeric(2002+i)
mes[[i]]$tipo <- "General"
}

for (i in 12:22){
mes[[i]] <- read.csv(paste("./MES/", i+1991,"H.csv",sep=""),sep=",", header= TRUE,stringsAsFactors=TRUE)
mes[[i]]$ano <- as.numeric(1991+i)
mes[[i]]$tipo <- "Hombres"
}

for (i in 23:33){
mes[[i]] <- read.csv(paste("./MES/", i+1980,"M.csv",sep=""),sep=",", header= TRUE,stringsAsFactors=TRUE)
mes[[i]]$ano <- as.numeric(1980+i)
mes[[i]]$tipo <- "Mujeres"
}

names(mes) <- c("Estado","Salud",  "IMSS-ORD",	"ISSSTE",	"IMSS-OP",	"DIF",	"PEMEX",	"SEDENA",	"SEMAR","Otras",	"Total")
)
mes <- ldply(mes, data.frame)

```


